# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."glance" = {
    image = "glanceapp/glance";
    volumes = [
      "/opt/docker/volumes/glance:/app/config:rw"
    ];
    ports = [
      "8080:8080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=glance"
      "--network=glance_default"
    ];
  };
  systemd.services."docker-glance" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-glance_default.service"
    ];
    requires = [
      "docker-network-glance_default.service"
    ];
    partOf = [
      "docker-compose-glance-root.target"
    ];
    wantedBy = [
      "docker-compose-glance-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-glance_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f glance_default";
    };
    script = ''
      docker network inspect glance_default || docker network create glance_default
    '';
    partOf = [ "docker-compose-glance-root.target" ];
    wantedBy = [ "docker-compose-glance-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-glance-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
