# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."jellyfin" = {
    image = "lscr.io/linuxserver/jellyfin:latest";
    environment = {
      "JELLYFIN_PublishedServerUrl" = "http://192.168.42.10";
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Europe/Berlin";
    };
    volumes = [
      "/mnt/media/jellyfin:/config:rw"
      "/mnt/media/media/movies:/data/movies:rw"
      "/mnt/media/media/tv:/data/tvshows:rw"
      "/mnt/media/media/yt:/data/youtube:rw"
    ];
    ports = [
      "8096:8096/tcp"
      "8920:8920/tcp"
      "7359:7359/udp"
      "1900:1900/udp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=jellyfin"
      "--network=jellyfin_default"
    ];
  };
  systemd.services."docker-jellyfin" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-jellyfin_default.service"
    ];
    requires = [
      "docker-network-jellyfin_default.service"
    ];
    partOf = [
      "docker-compose-jellyfin-root.target"
    ];
    wantedBy = [
      "docker-compose-jellyfin-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-jellyfin_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f jellyfin_default";
    };
    script = ''
      docker network inspect jellyfin_default || docker network create jellyfin_default
    '';
    partOf = [ "docker-compose-jellyfin-root.target" ];
    wantedBy = [ "docker-compose-jellyfin-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-jellyfin-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
