# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."navidrome" = {
    image = "deluan/navidrome:latest";
    environment = {
      "ND_COVERJPEGQUALITY" = "95";
      "ND_DEFAULTSHAREEXPIRATION" = "168h";
      "ND_ENABLEFAVOURITES" = "false";
      "ND_ENABLEINSIGHTSCOLLECTOR" = "false";
      "ND_ENABLESTARRATING" = "false";
    };
    volumes = [
      "/mnt/media/music:/music:ro"
      "/opt/docker/volumes/navidrome:/data:rw"
    ];
    ports = [
      "4533:4533/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=navidrome"
      "--network=navidrome_default"
    ];
  };
  systemd.services."docker-navidrome" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-navidrome_default.service"
    ];
    requires = [
      "docker-network-navidrome_default.service"
    ];
    partOf = [
      "docker-compose-navidrome-root.target"
    ];
    wantedBy = [
      "docker-compose-navidrome-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-navidrome_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f navidrome_default";
    };
    script = ''
      docker network inspect navidrome_default || docker network create navidrome_default
    '';
    partOf = [ "docker-compose-navidrome-root.target" ];
    wantedBy = [ "docker-compose-navidrome-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-navidrome-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
