# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."thelounge" = {
    image = "ghcr.io/thelounge/thelounge:latest";
    volumes = [
      "/opt/docker/volumes/thelounge:/var/opt/thelounge:rw"
    ];
    ports = [
      "9000:9000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=thelounge"
      "--network=thelounge_default"
    ];
  };
  systemd.services."docker-thelounge" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-thelounge_default.service"
    ];
    requires = [
      "docker-network-thelounge_default.service"
    ];
    partOf = [
      "docker-compose-thelounge-root.target"
    ];
    wantedBy = [
      "docker-compose-thelounge-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-thelounge_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f thelounge_default";
    };
    script = ''
      docker network inspect thelounge_default || docker network create thelounge_default
    '';
    partOf = [ "docker-compose-thelounge-root.target" ];
    wantedBy = [ "docker-compose-thelounge-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-thelounge-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
